# Generated by Django 2.1.5 on 2019-02-07 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190206_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrdetails',
            name='coachType',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
